
title: "NoteIt!"
email: 
description: >- # this means to ignore newlines until "baseurl:"
  This is a chrome extension!
baseurl: "/" 
url: "/" 
twitter_username: #
github_username:  #

sass:
  sass_dir: _sass

icon: /assets/img/new_logo.png